// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpXIbDhRI7fwJoo1vYD5oGJlWHaaPFNS4',
    appId: '1:826760163346:web:7b97026029e684365a68cb',
    messagingSenderId: '826760163346',
    projectId: 'mt-dhruv',
    authDomain: 'mt-dhruv.firebaseapp.com',
    storageBucket: 'mt-dhruv.appspot.com',
    measurementId: 'G-DR0ZTE8Q0H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBU1BFWX3pRvucIIqB1to1bg5OW_3FmIQE',
    appId: '1:826760163346:android:1627a996b5467f675a68cb',
    messagingSenderId: '826760163346',
    projectId: 'mt-dhruv',
    storageBucket: 'mt-dhruv.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiSxgPBqXt2JAybhOZYWlLwB6hi9TSRY0',
    appId: '1:826760163346:ios:088770848b6d6bba5a68cb',
    messagingSenderId: '826760163346',
    projectId: 'mt-dhruv',
    storageBucket: 'mt-dhruv.appspot.com',
    iosBundleId: 'com.example.mtDhruv',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDiSxgPBqXt2JAybhOZYWlLwB6hi9TSRY0',
    appId: '1:826760163346:ios:088770848b6d6bba5a68cb',
    messagingSenderId: '826760163346',
    projectId: 'mt-dhruv',
    storageBucket: 'mt-dhruv.appspot.com',
    iosBundleId: 'com.example.mtDhruv',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDpXIbDhRI7fwJoo1vYD5oGJlWHaaPFNS4',
    appId: '1:826760163346:web:8f11a5de4abbceaf5a68cb',
    messagingSenderId: '826760163346',
    projectId: 'mt-dhruv',
    authDomain: 'mt-dhruv.firebaseapp.com',
    storageBucket: 'mt-dhruv.appspot.com',
    measurementId: 'G-Y17JY9Y9ZE',
  );
}